### PR TITLE
Fixes for Moodle 4.1 compatibility

### LINKED ISSUE #152: Moodle 4.1 testing -> Some issues found
Tested on Ubuntu 22.04/PHP 8 with PostgreSQL 14 and MySQL 8.

I found the following issues:
- Use of deprecated get_all_user_name_fields function
- Obsolete "social" profile fields (icq, aim)

And some issues not directly related to 4.1:
- If no users are selected by the users cleaner, the queries fail due to passing an empty string to the `IN` SQL conditions.
- If all unit tests for the plugin and sub-plugins are run as a single suite, some tests fail due to the `dryrun` option being set in a static variable and not reset..

I also found an unrelated issue which appears to be PostgreSQL-specific, that I will log separately.

### PR DESCRIPTION
**Pull request by marxjohnson**
Resolves #152

### CODE REVIEW

File: cli/lib.php [hunk 1]
```diff
@@ -98,7 +98,7 @@ function safety_checks($dryrun) {
                 AND u.deleted = 0";
 
     if ($DB->count_records_sql($csql, $params)) {
-        $namefields = "u." . implode(', u.', get_all_user_name_fields());
+        $namefields = "u." . implode(', u.', \core_user\fields::get_name_fields());
```
Comment (brendanheywood) [inline cli/lib.php:101]: won't this break in older moodles where this doesn't exist yet? Either we need to detect the version and call the old function of pick a version and cut a new stable branch. It would be better have this in a unit test to expose that issue across versions too

Comment (marxjohnson) [reply cli/lib.php:101]: This function was introduced on Moodle 3.11, so you're right that it won't work on Moodle 3.10 which this branch supports (although it's no longer a supported release). Personally I prefer separate stable branches over version-detection code, as the latter feels like technical debt. Shall I create a new branch and change this PR's target?

Comment (brendanheywood) [reply cli/lib.php:101]: Yup please cut a new stable

Comment (marxjohnson) [reply cli/lib.php:101]: Actually, I think you'll have to do that for me. I don't have write access and GitHub doesn't have a way for me to submit a new branch from my repo to this one. I think it would make sense to call it MOODLE_311_STABLE as this and the removed user fields both apply from 3.11 onwards.

Comment (brendanheywood) [reply cli/lib.php:101]: I've made the new branch as a clone of the 310 one so you can make new prs against that now thanks

**Comment by marxjohnson** [comment]
Hi @brendanheywood ,
I've rebased this on the new stable branch, bumped the version and supported core versions, and added the new branch to the README. I think this is ready to merge now.

**Comment by marxjohnson** [comment]
@brendanheywood There we go, all green now on 3.11-4.1.

**Comment by danmarsden** [comment]
looks good to me - I've also updated the default branch here it github to "MOODLE_311_STABLE" - I didn't delete the old "master" branch as it will break AU pipelines using the older master branch.
