### PR TITLE
issue #166: Resolve unit test failure

### LINKED ISSUE #166: unit test failure test_it_outputs_header_and_footer post tracker MDL-79276
The following unit test is failing: 
```php
public function test_it_outputs_header_and_footer() {
    $html = $this->get_page();

    self::assertNotEmpty($html);
    self::assertStringContainsString('<html', $html);
    self::assertStringContainsString('</html', $html);
}
```

Specifically the last assertion, that it has the closing tag `</html` fails. This is because the closing tag is likely not caught in the output.  The full tracker merge request can be found here:  

 - https://github.com/moodle/moodle/commit/805ebbb4344ab8713dc7087b537f0c0d66d45863

However the main troubled lines are https://github.com/moodle/moodle/blob/main/lib/outputrenderers.php#L1559-L1571 which specifically removes the closing tags for body and html.

### PR DESCRIPTION
**Pull request by ScottVerbeek**
- Resolves issue post MDL-79276, adding the $CFG->closingtags if they exists

```
root@c3e2c38a9c70:/var/www/vanilla-403# XDEBUG_TRIGGER=1 vendor/bin/phpunit --testsuite cleaner_muc_testsuite --filter test_it_outputs_header_and_footer
Moodle 4.3.2+ (Build: 20240104), 40890bf181407b0a84990916070ff1b9b0357716
Php: 8.1.24, pgsql: 14.0 (Debian 14.0-1.pgdg110+1), OS: Linux 6.4.12-060412-generic x86_64
PHPUnit 9.5.28 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 00:00.814, Memory: 105.00 MB

OK (1 test, 3 assertions)
```

Closes #166 #168

### CODE REVIEW

File: cleaner/muc/tests/phpunit/output/index_renderer_test.php [hunk 1]
```diff
@@ -127,10 +127,13 @@ public function test_it_downloads_environment_config_file() {
     }
 
     private function get_page() {
+        global $CFG;
+
         ob_start();
         try {
             (new controller())->index();
             $html = ob_get_contents();
+            $html .= $CFG->closingtags ?? ''; // Fix for MDL-79276, if null then set fallback to empty string.
```
Comment (brendanheywood) [inline cleaner/muc/tests/phpunit/output/index_renderer_test.php:136]: as a fix this seems fine, but I'm unclear why test_it_downloads_environment_config_file exists and what it is asserting

So ok to land it, but if there isn't a good reason for this also happy to remove the unit test (or add some docs explaining why its useful)
